#!/usr/bin/env python3

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
  from PIL import Image
except ImportError:
  print("Pillow is required. Install it with: python3 -m pip install Pillow", file=sys.stderr)
  sys.exit(2)


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_HEADER = PROJECT_ROOT / "src" / "logo.h"


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
    description="Convert a PNG or JPEG into a little-endian RGB565 C header for the ILI9486L demo."
  )
  parser.add_argument("input", type=Path, help="Source image path")
  parser.add_argument("--width", type=int, default=480, help="Output width in pixels")
  parser.add_argument("--height", type=int, default=320, help="Output height in pixels")
  parser.add_argument(
    "--rotate",
    choices=("none", "cw", "ccw", "180"),
    default="none",
    help="Rotate image before resizing",
  )
  parser.add_argument(
    "--header",
    type=Path,
    default=DEFAULT_HEADER,
    help="Destination header path",
  )
  parser.add_argument(
    "--raw",
    type=Path,
    default=None,
    help="Optional destination for raw rgb565le bytes",
  )
  parser.add_argument(
    "--name",
    default="logo_raw",
    help="Base C symbol name for the generated byte array",
  )
  return parser.parse_args()


def sanitize_symbol(name: str) -> str:
  sanitized = []
  for char in name:
    if char.isalnum() or char == "_":
      sanitized.append(char)
    else:
      sanitized.append("_")

  result = "".join(sanitized).strip("_")
  if not result:
    result = "logo_raw"
  if result[0].isdigit():
    result = "_" + result
  return result


def resampling_filter() -> int:
  if hasattr(Image, "Resampling"):
    return Image.Resampling.LANCZOS
  return Image.LANCZOS


def rotation_mode(name: str):
  if name == "cw":
    return Image.Transpose.ROTATE_270
  if name == "ccw":
    return Image.Transpose.ROTATE_90
  if name == "180":
    return Image.Transpose.ROTATE_180
  return None


def load_rgb_image(path: Path, rotate: str, width: int, height: int) -> Image.Image:
  image = Image.open(path)

  if image.mode in ("RGBA", "LA") or "transparency" in image.info:
    rgba = image.convert("RGBA")
    background = Image.new("RGBA", rgba.size, (0, 0, 0, 255))
    image = Image.alpha_composite(background, rgba)

  image = image.convert("RGB")

  transpose = rotation_mode(rotate)
  if transpose is not None:
    image = image.transpose(transpose)

  return image.resize((width, height), resample=resampling_filter())


def image_to_rgb565le(image: Image.Image) -> bytes:
  output = bytearray()

  for red, green, blue in image.getdata():
    rgb565 = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
    output.append(rgb565 & 0xFF)
    output.append((rgb565 >> 8) & 0xFF)

  return bytes(output)


def write_header(path: Path, symbol: str, payload: bytes) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)

  lines = [f"const unsigned char {symbol}[] = {{\n"]

  for offset in range(0, len(payload), 12):
    chunk = payload[offset:offset + 12]
    values = ", ".join(f"0x{byte:02x}" for byte in chunk)
    suffix = "," if offset + len(chunk) < len(payload) else ""
    lines.append(f"  {values}{suffix}\n")

  lines.append("};\n")
  lines.append(f"const unsigned int {symbol}_len = {len(payload)};\n")

  path.write_text("".join(lines), encoding="ascii")


def main() -> int:
  args = parse_args()
  symbol = sanitize_symbol(args.name)
  image = load_rgb_image(args.input, args.rotate, args.width, args.height)
  payload = image_to_rgb565le(image)

  if args.raw is not None:
    args.raw.parent.mkdir(parents=True, exist_ok=True)
    args.raw.write_bytes(payload)

  write_header(args.header, symbol, payload)

  print(
    f"Wrote {len(payload)} bytes for {image.width}x{image.height} RGB565LE "
    f"to {args.header}"
  )
  if args.raw is not None:
    print(f"Wrote raw payload to {args.raw}")

  return 0


if __name__ == "__main__":
  sys.exit(main())
